name: rollerdash
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.3
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
